export default {
  domain: "mathix.dev",
  siteUrl: "https://mathix.dev",
  name: "Arnaud Gissinger",
  description: "Arnaud Gissinger is a French Solution Architect, 42 School Alumni and 2x founder. Passionate about Open Source, Web Development, Design, and Entrepreneurship. He did his first program at 10, sold his first software at 15, and launched his first startup at 19.",
  smallDescription: "Arnaud Gissinger is a French Passionate Solution Architect, previously 42 Student and founder.",
  blogDescription: "Just another tech blog from another dev, or maybe not? feedId:75543803563887616+userId:68304114010265600 feedId:75597336360181760+userId:68304114010265600",
  blogTitle: "Arnaud Gissinger's Blog",
  language: "en-US",
  sameAs: [
    "https://github.com/mathix420",
    "https://www.linkedin.com/in/agissing/",
    "https://bsky.app/profile/mathix.dev",
    "https://bento.me/agissing",
    "https://www.polywork.com/agissing/",
    "https://posts.cv/mathix",
    "https://read.cv/mathix",
    "https://stackoverflow.com/users/9799292/mathix420",
  ],
};
